#! /bin/sh

# scrip environment
ZERO_SRCDIR="@srcdir@"
ZERO_SCRIPT_DIR="/home/vendu/personal/OS-Zero/usr/lib/sh"
ZERO_PREFIX="/usr/local"
ZERO_EXEC_PREFIX="/usr/local"
ZERO_BINDIR="$ZERO_PREFIX/bin"
ZERO_SBINDIR="$ZERO_PREFIX/sbin"
ZERO_LIBEXECDIR="$ZERO_PREFIX/libexec"
ZERO_DATAROOTDIR="$ZERO_PREFIX/share"
ZERO_DATADIR="$ZERO_DATAROOTDIR"
ZERO_SYSCONFDIR="$ZERO_PREFIX/etc"
ZERO_SHAREDSTATEDIR="$ZERO_PREFIX/com"
ZERO_LOCALSTATEDIR="$ZERO_PREFIX/var"
ZERO_RUNSTATEDIR="$ZERO_LOCALSTATEDIR/run"
ZERO_INCLUDEDIR="$ZERO_PREFIX/include"
ZERO_OLDINCLUDEDIR="/usr/include"
ZERO_DOCDIR="$ZERO_DATAROOTDIR/doc/@pkgname@"
ZERO_INFODIR="$ZERO_DATAROOTDIR/info"
ZERO_LIBDIR="$ZERO_EXEC_PREFIX/lib"
ZERO_LOCALEDIR="$ZERO_DATAROOTDIR/locale"
ZERO_MANDIR="$ZERO_DATAROOTDIR/man"
ZERO_MAN1DIR="$ZERO_MANDIR/man1"
ZERO_MAN1DIR="$ZERO_MANDIR/man2"
ZERO_MANEXT=".1"
ZERO_MAN1EXT=".1"
ZERO_MAN1EXT=".2"

# signal numbers
# The signals that are known to be safe to trap.
ZERO_TRAPEXIT=0
ZERO_SIGHUP=1
ZERO_SIGINT=2
ZERO_SIGPIPE=13
ZERO_SIGTERM=15

# Other signals.
ZERO_SIGQUIT=3
ZERO_SIGILL=4
ZERO_SIGABRT=6
ZERO_SIGFPE=8
ZERO_SIGKILL=9
ZERO_SIGSEGV=11
ZERO_SIGALRM=14
